# Generated by Django 5.0.6 on 2024-12-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_question_answer_alter_question_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='questions_csv',
        ),
    ]
