# Generated by Django 5.0.6 on 2024-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_remove_jobpost_questions_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('discipline', models.CharField(max_length=100, verbose_name='Discipline')),
                ('area_of_expertise', models.TextField(verbose_name='Area of Expertise')),
            ],
        ),
    ]
